DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    EMAIL VARCHAR(100) PRIMARY KEY,
    PHN_NO VARCHAR(15) NOT NULL,
    PASSWRD VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS QUESTION;
CREATE TABLE QUESTION(
    QUES_U_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAIL VARCHAR(100) NOT NULL,
    QUESTION VARCHAR(1000) NOT NULL,
    DESCRIP VARCHAR(1000),
    FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL)
);

DROP TABLE IF EXISTS QUERIES;
CREATE TABLE QUERIES(
    QUERS_U_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAIL VARCHAR(100) NOT NULL,
    Q_MSG VARCHAR(1000) NOT NULL,
    REPLY VARCHAR(3000) NOT NULL,
    FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL)
);

DROP TABLE IF EXISTS UPLOADS;
CREATE TABLE UPLOADS(
    IMG_U_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAIL VARCHAR(100) NOT NULL,
    FILE_NAME VARCHAR(1000) NOT NULL,
    IMG_FILE BLOB NOT NULL,
    PREDICTION VARCHAR(1000) NOT NULL,
    FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL)
);

DROP TABLE IF EXISTS DOCTORS;
CREATE TABLE DOCTORS(
    DOCTOR_U_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    D_NAME VARCHAR(100) NOT NULL,
    PH_NO VARCHAR(15),
    D_LOCATION VARCHAR(1000) NOT NULL,
    LATITUDE REAL,
    LONGITUDE REAL,
    CENTERS VARCHAR(3000),
    TIMING VARCHAR(50),
    DISEASE_TYPE VARCHAR(100) NOT NULL
);